openapi: '3.0.2'
info:
  title: Core API
  version: '0.0.1'
paths:
  /products: 
      get: 
        tags:
          - Product
        summary: ดูรายการสินค้าคงคลัง
        responses:
          '200': 
            description: OK
  /test:
    description: Test
    get: 
      responses:
        '200': 
          description: OK
        '400': 
          description: Error
        '401':
          description: Unauthenticate
          
  /products/{product_id}:
    get: 
      tags:
        - Product
      summary: ดูสินค้า
      parameters:
        - in: path
          name: product_id 
          schema: 
            type: integer
          required: true
      responses:
        '200':
          description: Object of product
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status: 
                    type: string 
                    example: OK
                  message: 
                    type: string 
                    example: Edited successfully


