openapi: '3.0.2'
info:
  title: Core API
  version: '0.0.1'
paths:
  /products: 
      get: 
        tags:
          - Product
        summary: ดูรายการสินค้าคงคลัง
        responses:
          '200': 
            description: OK
  /test:
    description: Test
    get: 
      responses:
        '200': 
          description: OK
        '400': 
          description: Error
        '401':
          description: Unauthenticate


