openapi: '3.0.2'
info:
  title: Core API
  version: '0.0.1'
paths:
  /test:
    description: Test
    get: 
      responses:
        '200': 
          description: OK
        '400': 
          description: Error
        '401':
          description: Unauthenticate


